### ISSUE TITLE
Culture invariant priority element

### ISSUE THREAD

**Issue by ViGiLnT** [marceldigital/Umbraco-XML-Sitemap#1]
Hi!

First of all, thanks for the useful plugin for Umbraco.

I have a problem where the priority element is culture dependent, so in cultures like mine, Portuguese, the priority value has a comma (",") instead of a dot ("."). This throws an error in Google Webmaster Tools.

I fixed it by throwing in a CultureInfo.InvariantCulture parameter in file UmbracoContent.cs:

`new XElement("priority", Priority.ToString("N1", CultureInfo.InvariantCulture))`

I tried to create a pull request but it's not possible. It would be nice if you could include this change in the next version.

Thanks,

André Santos

**Comment by vipervf1** [comment]
@ViGiLnT 
Thanks for finding this! I've updated the package with your change. 

Update to v1.0.13 and you'll be good to go.
https://www.nuget.org/packages/MarcelDigital.UmbracoExtensions.XmlSitemap/1.0.13
